export interface Country {
  id: string;
  name: string;
  continent: string;
}

// Hardcoded countries with ISO codes as IDs for consistency
export const HARDCODED_COUNTRIES: Country[] = [
  { id: "au", name: "Australia", continent: "Oceania" },
  { id: "za", name: "South Africa", continent: "Africa" },
  { id: "id", name: "Indonesia", continent: "Asia" },
  { id: "us", name: "United States", continent: "North America" },
  { id: "pt", name: "Portugal", continent: "Europe" },
  { id: "fr", name: "France", continent: "Europe" },
  { id: "es", name: "Spain", continent: "Europe" },
  { id: "br", name: "Brazil", continent: "South America" },
  { id: "cr", name: "Costa Rica", continent: "North America" },
  { id: "mx", name: "Mexico", continent: "North America" },
  { id: "nz", name: "New Zealand", continent: "Oceania" },
  { id: "jp", name: "Japan", continent: "Asia" },
  { id: "ma", name: "Morocco", continent: "Africa" },
  { id: "fj", name: "Fiji", continent: "Oceania" },
  { id: "mv", name: "Maldives", continent: "Asia" },
  { id: "ao", name: "Angola", continent: "Africa" },
  { id: "mz", name: "Mozambique", continent: "Africa" },
  { id: "gb", name: "United Kingdom", continent: "Europe" },
  { id: "sv", name: "El Salvador", continent: "North America" },
  { id: "pe", name: "Peru", continent: "South America" },
  { id: "cl", name: "Chile", continent: "South America" },
  { id: "ni", name: "Nicaragua", continent: "North America" },
  { id: "pa", name: "Panama", continent: "North America" },
  { id: "ph", name: "Philippines", continent: "Asia" },
  { id: "lk", name: "Sri Lanka", continent: "Asia" },
  { id: "tw", name: "Taiwan", continent: "Asia" },
  { id: "th", name: "Thailand", continent: "Asia" },
  { id: "ie", name: "Ireland", continent: "Europe" },
  { id: "es-cn", name: "Canary Islands", continent: "Europe" },
  { id: "us-hi", name: "Hawaii", continent: "North America" },
  { id: "ec", name: "Ecuador", continent: "South America" },
  { id: "mg", name: "Madagascar", continent: "Africa" },
  { id: "ws", name: "Samoa", continent: "Oceania" },
  { id: "pf", name: "French Polynesia (Tahiti)", continent: "Oceania" },
  { id: "na", name: "Namibia", continent: "Africa" },
  { id: "ga", name: "Gabon", continent: "Africa" },
  { id: "lr", name: "Liberia", continent: "Africa" },
  { id: "sn", name: "Senegal", continent: "Africa" },
  { id: "yt", name: "Mayotte", continent: "Africa" },
  { id: "fo", name: "Faroe Islands", continent: "Africa" },
  { id: "mu", name: "Mauritius", continent: "Africa" },
  { id: "cape-verde", name: "Cape Verde", continent: "Africa" },
];
