import { Router, Response } from "express";
import { IntelligenceService } from "../services/intelligenceService";
import { authenticateToken, AuthRequest } from "../middleware/auth";

const router = Router();

// Existing daily report (mini-intel)
router.get("/report", async (req, res) => {
  const { beach, windSpeed, windDir, swellHeight, swellPeriod, swellDir, score, persona, date, trend } = req.query;

  if (!beach || !persona || !date) {
    return res.status(400).json({ error: "Missing required parameters" });
  }

  try {
    const report = await IntelligenceService.getReport(
        beach as string,
        parseFloat(windSpeed as string || "0"),
        windDir as string || "N",
        parseFloat(swellHeight as string || "0"),
        parseFloat(swellPeriod as string || "0"),
        swellDir as string || "W",
        parseFloat(score as string || "0"),
        (persona as string).toUpperCase(),
        date as string,
        trend as string
    );

    res.json({ report });
  } catch (error) {
    res.status(500).json({ error: "Failed to generate AI intelligence" });
  }
});

/**
 * Premium Weekly Strategic AI Report
 * Costs 1 Credit (R1)
 */
router.post("/weekly", authenticateToken, async (req: AuthRequest, res: Response) => {
  const { beachId, date, persona } = req.body;
  const userId = req.user?.id;

  if (!beachId || !date || !userId) {
    return res.status(400).json({ error: "Missing required parameters: beachId, date, and user authentication are required." });
  }

  try {
    const result = await IntelligenceService.getWeeklyReportForBeach(
      beachId,
      date,
      userId,
      persona
    );

    res.json(result);
  } catch (error: any) {
    console.error("[IntelligenceRoute] Weekly report error:", error);
    
    if (error.message === "INSUFFICIENT_CREDITS") {
      return res.status(402).json({ 
        error: "Insufficient credits", 
        message: "You need at least 1 credit to generate a Weekly Strategic Report." 
      });
    }

    if (error.message === "Beach not found") {
      return res.status(404).json({ error: "Beach not found" });
    }

    res.status(500).json({ error: "Failed to generate weekly tactical intelligence" });
  }
});

/**
 * Share Intelligence Report via Email
 */
router.post("/share-email", authenticateToken, async (req: AuthRequest, res: Response) => {
  const { email, beachName, reportText } = req.body;

  if (!email || !beachName || !reportText) {
    return res.status(400).json({ error: "Missing required parameters for sharing" });
  }

  try {
    const { sendEmail } = await import("../lib/email");
    
    const htmlReport = `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #f8fafc;">
        <h2 style="color: #2563eb; margin-bottom: 4px; text-transform: uppercase;">Tactical Intel: ${beachName}</h2>
        <p style="color: #64748b; font-size: 12px; margin-bottom: 20px;">WEEKLY STRATEGIC REPORT • GENERATED BY TIDE RAIDER AI</p>
        <div style="background-color: white; padding: 20px; border-radius: 8px; border: 1px solid #f1f5f9; white-space: pre-wrap; font-size: 14px; line-height: 1.6; color: #1e293b;">
          ${reportText.replace(/\n/g, '<br/>')}
        </div>
        <div style="margin-top: 24px; text-align: center; font-size: 11px; color: #94a3b8;">
          © ${new Date().getFullYear()} Tide Raider. Sent by a friend who's ready to raid.
        </div>
      </div>
    `;

    const success = await sendEmail(
      email,
      `Tactical Share: ${beachName} Intelligence Report 🌊`,
      htmlReport
    );

    if (success) {
      res.json({ success: true });
    } else {
      res.status(500).json({ error: "Failed to send intelligence email" });
    }
  } catch (error) {
    console.error("[IntelligenceRoute] Sharing error:", error);
    res.status(500).json({ error: "Internal server error during sharing" });
  }
});

export default router;
